In [1]:
import pandas as pd 
import numpy as np

In [ ]:
data = pd.read_csv('data.csv/Insurance Penetration.csv')

In [2]:
def clean_data(filepath):
    data = pd.read_csv(filepath)
    
    #converting the disposable income to a standard format
    mapping = {
    'Less than 1000': 800,
    '1000 - 2000': 1600,
    '2000 - 3000': 2500,
    'More than 3000': 4000
}

    data['income'] = data['Disposable Income/Allowance'].map(mapping)
        
    #create our target column using Do you have any Life or Non-Life Insurance Policy column
    target_mapping = {
    'Yes': 1,
    'No': 0}    

    data['target'] = data['Do you have any Life or Non-Life Insurance Policy'].map(target_mapping)
    
    data['target'] = data['target'].fillna(0)
    
    data['target'] = data['target'].astype(int)
    
    # remove unimportant columns from the dataset
    leaky_cols = ['Timestamp','Username','Gender','Disposable Income/Allowance','Do you have any Life or Non-Life Insurance Policy']
    
    data = data.drop(columns = leaky_cols)
    
    return data

In [6]:
n_data = clean_data('data.csv/Insurance Penetration.csv')
n_data.head(10)

,Educational Background,Occupational Status,Educational Level,Statutory Requirements,Personal Benefits,Technological Advancement,Religious Beliefs / Affiliations,What is your past or current experience with insurance companies.,Did this experience influence your perception and/or decision to buy insurance policies.,income,target
0,Tertiary,Student,Yes,Yes,Yes,No,No,Neutral,No,800,0
1,Tertiary,Student,Yes,Yes,Yes,Yes,Yes,Neutral,No,800,0
2,Secondary,Employed,Yes,Yes,Yes,Yes,Yes,Good,Maybe,800,0
3,Tertiary,Employed,Yes,Yes,Yes,Yes,Yes,Bad,No,1600,0
4,Tertiary,Student,No,No,No,Yes,No,Neutral,Yes,800,0
5,Tertiary,Student,Yes,Yes,Yes,Yes,Yes,Neutral,No,800,0
6,Tertiary,Student,Yes,Yes,Yes,Yes,Yes,Good,Yes,800,0
7,Tertiary,Employed,Yes,Yes,Yes,Yes,Yes,Neutral,Yes,1600,1
8,Tertiary,Student,Yes,Yes,Yes,Yes,No,Neutral,Maybe,800,0
9,Tertiary,Employed,Yes,Yes,Yes,Yes,No,Neutral,No,2500,0

In [7]:
data.head(50)

NameError: name 'data' is not defined

In [ ]:
mapping = {
    'Less than 1000': 800,
    '1000 - 2000': 1600,
    '2000 - 3000': 2500,
    'More than 3000': 4000
}

data['income'] = data['Disposable Income/Allowance'].map(mapping)

In [ ]:
data['income'].head(50)

In [ ]:
target_mapping = {
    'Yes':1,
    'No':0
}

data['target'] = data['Do you have any Life or Non-Life Insurance Policy'].map(target_mapping)

In [ ]:
data['target'].head(40)

In [4]:
new_data = clean_data('data.csv/ip_data.csv')

In [5]:
new_data.head()

,Educational Background,Occupational Status,Educational Level,Statutory Requirements,Personal Benefits,Technological Advancement,Religious Beliefs / Affiliations,What is your past or current experience with insurance companies.,Did this experience influence your perception and/or decision to buy insurance policies.,income,target
0,Tertiary,Student,Yes,Yes,Yes,No,No,Neutral,No,800.0,0
1,Tertiary,Student,Yes,Yes,Yes,Yes,Yes,Neutral,No,800.0,0
2,Secondary,Employed,Yes,Yes,Yes,Yes,Yes,Good,Maybe,800.0,0
3,Tertiary,Employed,Yes,Yes,Yes,Yes,Yes,Bad,No,1600.0,0
4,Tertiary,Student,No,No,No,Yes,No,Neutral,Yes,800.0,0

In [11]:
new_data.to_csv('data.csv/clean_data.csv')

In [16]:
df = pd.read_csv('data.csv/clean_data.csv')
df.head(5)

,Unnamed: 0,Educational Background,Occupational Status,Educational Level,Statutory Requirements,Personal Benefits,Technological Advancement,Religious Beliefs / Affiliations,What is your past or current experience with insurance companies.,Did this experience influence your perception and/or decision to buy insurance policies.,income,target
0,0,Tertiary,Student,Yes,Yes,Yes,No,No,Neutral,No,800.0,0
1,1,Tertiary,Student,Yes,Yes,Yes,Yes,Yes,Neutral,No,800.0,0
2,2,Secondary,Employed,Yes,Yes,Yes,Yes,Yes,Good,Maybe,800.0,0
3,3,Tertiary,Employed,Yes,Yes,Yes,Yes,Yes,Bad,No,1600.0,0
4,4,Tertiary,Student,No,No,No,Yes,No,Neutral,Yes,800.0,0

,Educational Background,Occupational Status,Educational Level,Statutory Requirements,Personal Benefits,Technological Advancement,Religious Beliefs / Affiliations,What is your past or current experience with insurance companies.,Did this experience influence your perception and/or decision to buy insurance policies.,income,target
0,Tertiary,Student,Yes,Yes,Yes,No,No,Neutral,No,800.0,0
1,Tertiary,Student,Yes,Yes,Yes,Yes,Yes,Neutral,No,800.0,0
2,Secondary,Employed,Yes,Yes,Yes,Yes,Yes,Good,Maybe,800.0,0
3,Tertiary,Employed,Yes,Yes,Yes,Yes,Yes,Bad,No,1600.0,0
4,Tertiary,Student,No,No,No,Yes,No,Neutral,Yes,800.0,0
...,...,...,...,...,...,...,...,...,...,...,...
252,Other,Employed,No,Yes,Yes,No,No,Neutral,Maybe,800.0,0
253,Tertiary,Employed,Yes,Yes,Yes,Yes,No,Neutral,No,4000.0,1
254,Tertiary,Employed,Yes,Yes,Yes,No,No,Good,Maybe,4000.0,1
255,Other,Employed,Yes,Yes,Yes,Yes,Yes,Neutral,Maybe,4000.0,1
256,Tertiary,Student,Yes,Yes,Yes,Yes,Yes,Neutral,Maybe,NaN,0

In [33]:
def clean_data2(filepath):
    data = pd.read_csv(filepath)
    
    #converting the disposable income to a standard format
    mapping = {
    'Less than 1000': 800,
    '1000 - 2000': 1600,
    '2000 - 3000': 2500,
    'More than 3000': 4000
    }
    
    data['income'] = data['Disposable Income/Allowance'].map(mapping)
    
        
    #create our target column using Do you have any Life or Non-Life Insurance Policy column
    target_mapping = {
    'Yes': 1,
    'No': 0} 
  
    educational_mapping = {
        'Secondary':0,
        'Tertiary':1}
    
    occupational_mapping = {
        'Student':0,
        'Unemployed':1,
        'Employed':2
    }
    

    same_mapping = {
        'No':0,
        'Yes':1
    }
    
    experience_mapping = {
        'No':0,
        'Maybe':0,
        'Yes':1
    }
    
    past_experience = {
        "Bad":0,
        "Neutral":1,
        "Good":2
    }
    
    data['educ_bag'] = data['Educational Background'].map(educational_mapping)
    
    data['educ_bag'] = data['educ_bag'].astype(int)
    
    data['occ_status'] = data['Occupational Status'].map(occupational_mapping)
    
    data['state_req'] = data['Statutory Requirements'].map(same_mapping)
    data['pers_ben'] = data['Personal Benefits'].map(same_mapping)
    data['tech_ad'] = data['Technological Advancement'].map(same_mapping)
    data['rel_aff'] = data['Religious Beliefs / Affiliations'].map(same_mapping)
    data['edu_level'] = data['Educational Level'].map(same_mapping)
    data['decision_influence'] = data['Did this experience influence your perception and/or decision to buy insurance policies.'].map(experience_mapping)
    
    data['experi_impli'] = data['What is your past or current experience with insurance companies.'].map(past_experience)
    
    data['target'] = data['Do you have any Life or Non-Life Insurance Policy'].map(target_mapping)
    
    data['target'] = data['target'].fillna(0)
    
    data['target'] = data['target'].astype(int)
    
    # remove unimportant columns from the dataset
    leaky_cols = ['Disposable Income/Allowance','Do you have any Life or Non-Life Insurance Policy','Educational Background','Occupational Status','Statutory Requirements','Personal Benefits','Technological Advancement','Religious Beliefs / Affiliations','Educational Level','Did this experience influence your perception and/or decision to buy insurance policies.','What is your past or current experience with insurance companies.']
    
    data = data.drop(columns = leaky_cols)
    
    data = data.dropna()
    
    return data

In [34]:
df = clean_data2('data.csv/new_data.csv')
df.head(5)

,income,educ_bag,occ_status,state_req,pers_ben,tech_ad,rel_aff,edu_level,decision_influence,experi_impli,target
0,800.0,1,0,1,1,0,0,1,0,1,0
1,800.0,1,0,1,1,1,1,1,0,1,0
2,800.0,0,2,1,1,1,1,1,0,2,0
3,1600.0,1,2,1,1,1,1,1,0,0,0
4,800.0,1,0,0,0,1,0,0,1,1,0

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 256 entries, 0 to 256
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   income              256 non-null    float64
 1   educ_bag            256 non-null    int32
 2   occ_status          256 non-null    int64
 3   state_req           256 non-null    int64
 4   pers_ben            256 non-null    int64
 5   tech_ad             256 non-null    int64
 6   rel_aff             256 non-null    int64
 7   edu_level           256 non-null    int64
 8   decision_influence  256 non-null    int64
 9   experi_impli        256 non-null    int64
 10  target              256 non-null    int32
dtypes: float64(1), int32(2), int64(8)
memory usage: 22.0 KB

In [38]:
df.to_csv('data.csv/new_clean_data.csv', index = False)